name: zevent_bus
description: Simple event notification
version: 0.0.2
homepage: https://github.com/eyesoffish/zevent_bus/tree/main/zevent_bus

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
